### Váriaveis de ambiente

@base_url = http://127.0.0.1:8000

### Teste de conexão com a API
GET {{base_url}}/ HTTP/1.1
Accept: application/json

### Criação de uma série
POST {{base_url}}/ HTTP/1.1
Content-Type: application/json

{
    "titulo": "Rick and Morty",
    "descricao": "Avô e neto em altas aventuras interdimensionais",
    "ano_lancamento": 2013
}

### Obtenção de todas as séries
GET {{base_url}}/series HTTP/1.1
Accept: application/json

### Atualização de uma série
PUT {{base_url}}/update/99 HTTP/1.1
Content-Type: application/json

{
    "titulo": "Breaking Bad",
    "descricao": "Professor e ex-aluno cozinham",
    "ano_lancamento": 2008
}

### Tentativa de atualização de uma série inexistente
